<?php

use Illuminate\Database\Seeder;

class UploadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('uploads')->delete();
        
        \DB::table('uploads')->insert(array (
            0 => 
            array (
                'id' => 1,
                'path' => '/uploads/posts/images',
                'original_name' => 'placehoder-black.jpg',
                'caption' => NULL,
                'caption_ar' => '',
                'file_name' => '6cb3a4e9188cfd280997cc52acd01155.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 1,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-21 14:21:04',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            1 => 
            array (
                'id' => 2,
                'path' => '/uploads/posts/images',
                'original_name' => '4.jpg',
                'caption' => '',
                'caption_ar' => NULL,
                'file_name' => 'c0a42045fe459dd26db08ed22a77a4d6.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 2,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-21 14:23:07',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            2 => 
            array (
                'id' => 3,
                'path' => '/uploads/posts/images',
                'original_name' => '1.jpg',
                'caption' => NULL,
                'caption_ar' => '',
                'file_name' => '8048273b809f44daace4dffc1bbf44bf.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 3,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-21 14:23:18',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            3 => 
            array (
                'id' => 4,
                'path' => '/uploads/landing',
                'original_name' => '1.mp4',
                'caption' => '',
                'caption_ar' => NULL,
                'file_name' => '1b02cafca5aeaae0fc0ca8463ac8b8e6.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 1,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:56:47',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            4 => 
            array (
                'id' => 5,
                'path' => '/uploads/landing',
                'original_name' => '2.mp4',
                'caption' => NULL,
                'caption_ar' => '',
                'file_name' => 'cae70b454ab9dd806821d9179026890c.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 2,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:56:57',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            5 => 
            array (
                'id' => 6,
                'path' => '/uploads/landing',
                'original_name' => '3.mp4',
                'caption' => '',
                'caption_ar' => NULL,
                'file_name' => '3d6c67b28fc450a1d3849b4edb81b414.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 3,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:57:06',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            6 => 
            array (
                'id' => 7,
                'path' => '/uploads/landing',
                'original_name' => '4.mp4',
                'caption' => NULL,
                'caption_ar' => '',
                'file_name' => '6a667f0cfeb85bef84f0d556caea387d.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 4,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:57:16',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            7 => 
            array (
                'id' => 8,
                'path' => '/uploads/landing',
                'original_name' => '5.mp4',
                'caption' => '',
                'caption_ar' => NULL,
                'file_name' => '7a42f6adedb08832ea5d3b32606b601c.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 5,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:57:27',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            8 => 
            array (
                'id' => 9,
                'path' => '/uploads/landing',
                'original_name' => '6.mp4',
                'caption' => NULL,
                'caption_ar' => '',
                'file_name' => '7c64c0f10f9b29fc3637cbec2e59330c.mp4',
                'mime_type' => 'video/mp4',
                'template' => '',
                'uploadable_id' => 6,
                'uploadable_type' => 'App\\Models\\LandingElement',
                'status' => 0,
                'created_at' => '2018-11-22 05:57:37',
                'updated_at' => '2018-11-22 06:16:38',
            ),
            9 => 
            array (
                'id' => 10,
                'path' => '/uploads/posts/images',
                'original_name' => '2.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'e8323ece3e10d1e9976459042f2ab1b5.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 4,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 05:58:11',
                'updated_at' => '2018-11-22 05:58:11',
            ),
            10 => 
            array (
                'id' => 14,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => 'Qasimiyah-landscape.jpg',
                'caption' => 'Photograph by Hatem Hatem',
                'caption_ar' => 'تصوير حاتم حاتم',
                'file_name' => '2d09158c7b9090bd8d5a63badad80bc6.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 2,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:01:31',
                'updated_at' => '2018-11-22 06:01:31',
            ),
            11 => 
            array (
                'id' => 15,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '1-landscape.jpg',
                'caption' => 'Photograph by Ieva Saudargaitė',
                'caption_ar' => 'تصوير ايڤا ساودارجيته',
                'file_name' => 'd4ffe6065d1e0d9049adf689b024f00c.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 9,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:18:03',
                'updated_at' => '2018-11-22 06:18:03',
            ),
            12 => 
            array (
                'id' => 16,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '2-landscape.jpg',
                'caption' => 'Photograph by Ieva Saudargaitė',
                'caption_ar' => 'تصوير ايڤا ساودارجيته',
                'file_name' => '45922f2527155591325671c4aaad3d42.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 10,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:18:03',
                'updated_at' => '2018-11-22 06:18:03',
            ),
            13 => 
            array (
                'id' => 17,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '3-landscape.jpg',
                'caption' => 'Photograph by Paul Gorra',
                'caption_ar' => 'تصوير بول غره',
                'file_name' => 'f8bcf2b8947329f525053ad104b75c04.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 11,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:18:03',
                'updated_at' => '2018-11-22 06:18:03',
            ),
            14 => 
            array (
                'id' => 18,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '4-landscape.jpg',
                'caption' => 'Photograph by Ieva Saudargaitė',
                'caption_ar' => 'تصوير ايڤا ساودارجيته',
                'file_name' => 'ac08086822792d4af940fe69fc3cc5e9.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 12,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:18:03',
                'updated_at' => '2018-11-22 06:18:03',
            ),
            15 => 
            array (
                'id' => 19,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '5-landscape.jpg',
                'caption' => 'Photograph by Ieva Saudargaitė',
                'caption_ar' => 'تصوير ايڤا ساودارجيته',
                'file_name' => 'd1b795e8309cf9f9e7a3c8f640960add.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 13,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:18:03',
                'updated_at' => '2018-11-22 06:18:03',
            ),
            16 => 
            array (
                'id' => 22,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '4e4c444986aacec1353dd5130270075e.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 5,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:25:06',
                'updated_at' => '2018-11-22 06:25:23',
            ),
            17 => 
            array (
                'id' => 24,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '453fffe62e160e6fc80d44f8c80bb067.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 6,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:26:37',
                'updated_at' => '2018-11-22 06:26:50',
            ),
            18 => 
            array (
                'id' => 26,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '5e81070da12baee0c5e81309006ad39a.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 7,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:26:50',
                'updated_at' => '2018-11-22 06:26:50',
            ),
            19 => 
            array (
                'id' => 28,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '6c490484f222bf40906ac38df1c2187c.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 7,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:37:50',
                'updated_at' => '2018-11-22 06:37:50',
            ),
            20 => 
            array (
                'id' => 29,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'b2896289e38223267beacf2b5a08a495.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 8,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:37:50',
                'updated_at' => '2018-11-22 06:38:30',
            ),
            21 => 
            array (
                'id' => 30,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'fca07bba56442d21cc4cd76607eb11f6.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 8,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:37:50',
                'updated_at' => '2018-11-22 06:37:50',
            ),
            22 => 
            array (
                'id' => 31,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '75d101cefad7bda719200f90fa213254.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 9,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:38:30',
                'updated_at' => '2018-11-22 06:38:30',
            ),
            23 => 
            array (
                'id' => 32,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'supc-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'b5eebc90675c71e9c4f5e9db201efb10.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 9,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:38:30',
                'updated_at' => '2018-11-22 06:38:30',
            ),
            24 => 
            array (
                'id' => 33,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'AUS-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '742d75d874ad08578455b38396f52328.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 10,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:39:50',
                'updated_at' => '2018-11-22 06:39:50',
            ),
            25 => 
            array (
                'id' => 34,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'AUS-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '0cd402084ca1a346d87258d4fc8b4eb5.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 10,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:39:50',
                'updated_at' => '2018-11-22 06:39:50',
            ),
            26 => 
            array (
                'id' => 35,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'beeah-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'd3589d2222b35272af08e22fdcd387e0.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 11,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:40:34',
                'updated_at' => '2018-11-22 06:40:34',
            ),
            27 => 
            array (
                'id' => 36,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'beeah-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '3d5c5608403adc744c8e8362033149b5.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 11,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:40:34',
                'updated_at' => '2018-11-22 06:40:34',
            ),
            28 => 
            array (
                'id' => 37,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'sharjah-government-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '324a6de1eaeaa4ceb908499736412a9c.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 12,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:41:35',
                'updated_at' => '2018-11-22 06:41:35',
            ),
            29 => 
            array (
                'id' => 38,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'sharjah-government-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '29aa2cf15bc4bed492664d96942d7896.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 12,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:41:35',
                'updated_at' => '2018-11-22 06:41:35',
            ),
            30 => 
            array (
                'id' => 39,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'sharjah-ar-landscapet.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '53c96033fd58eb02124486c92be36dfb.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 13,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:42:04',
                'updated_at' => '2018-11-22 06:42:04',
            ),
            31 => 
            array (
                'id' => 40,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'sharjah-ar-landscapet.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'abc6d5354f2d0bde50c3f42017c0fbbc.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 13,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 06:42:04',
                'updated_at' => '2018-11-22 06:42:04',
            ),
            32 => 
            array (
                'id' => 41,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '2-landscape.jpg',
                'caption' => 'Photograph by Ieva Saudargaitė',
                'caption_ar' => 'تصوير ايڤا ساودارجيته',
                'file_name' => 'e63f69d284ee2f63a863b771f6206bd4.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 8,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:02:11',
                'updated_at' => '2018-11-22 11:02:11',
            ),
            33 => 
            array (
                'id' => 42,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '1-landscape.jpg',
                'caption' => 'Photograph by Hatem Hatem',
                'caption_ar' => 'تصوير حاتم حاتم',
                'file_name' => 'f65c9f2872b70ab4f877ecc38b4e66f1.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 14,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:08:19',
                'updated_at' => '2018-11-22 11:08:19',
            ),
            34 => 
            array (
                'id' => 43,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '1-landscape.jpg',
                'caption' => 'Photograph by Rabee Younes',
                'caption_ar' => 'تصوير ربيع يونس',
                'file_name' => 'daf38ec552d7f6bd9a38102e17b0f903.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 15,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:09:13',
                'updated_at' => '2018-11-22 11:09:13',
            ),
            35 => 
            array (
                'id' => 46,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'climate-3-landscape.jpg',
                'caption' => 'Photograph by Stefania D\'Alessandro',
                'caption_ar' => 'تصوير ستيفانيا داليساندرو',
                'file_name' => '4c6297987b53bafcfd4ffa543ba0e782.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 14,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:23:17',
                'updated_at' => '2018-11-22 11:23:17',
            ),
            36 => 
            array (
                'id' => 47,
                'path' => '/uploads/posts/images',
                'original_name' => 'climate-1.jpg',
                'caption' => 'Photograph by Amin Alsaden',
                'caption_ar' => 'تصوير امين السادن',
                'file_name' => 'fb729f66b95bbc6c7b8397292cc2b82b.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 15,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:33:24',
                'updated_at' => '2018-11-22 11:33:24',
            ),
            37 => 
            array (
                'id' => 48,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'climate-1-landscape.jpg',
                'caption' => 'Photograph by Amin Alsaden',
                'caption_ar' => 'تصوير امين السادن',
                'file_name' => 'aa1b6948b479d5460dc90f95c12515d2.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 15,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:33:24',
                'updated_at' => '2018-11-22 11:33:24',
            ),
            38 => 
            array (
                'id' => 49,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'climate-1-landscape.jpg',
                'caption' => 'Photograph by Amin Alsaden',
                'caption_ar' => 'تصوير امين السادن',
                'file_name' => 'd2ac5ab11f617a31b7d5dad492459474.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 15,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:33:24',
                'updated_at' => '2018-11-22 11:33:24',
            ),
            39 => 
            array (
                'id' => 50,
                'path' => '/uploads/posts/images',
                'original_name' => 'climate-3.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '2dafad815ca2ab6282bccc3d1d7a376d.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 16,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:34:10',
                'updated_at' => '2018-11-22 11:34:10',
            ),
            40 => 
            array (
                'id' => 51,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'climate-3-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'd1774c05a71e88a1e32c811aa3ff91dd.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 16,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:34:10',
                'updated_at' => '2018-11-22 11:35:19',
            ),
            41 => 
            array (
                'id' => 52,
                'path' => '/uploads/posts/landscape/images/original',
                'original_name' => 'climate-3-landscape.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'd46f19a3361aa2e1ce5c95aa7a8f4352.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'original',
                'uploadable_id' => 16,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:34:10',
                'updated_at' => '2018-11-22 11:34:10',
            ),
            42 => 
            array (
                'id' => 53,
                'path' => '/uploads/posts/images',
                'original_name' => 'climate-2.jpg',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '5a319436c387fefdbd18bd4c7902dccd.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 14,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:34:34',
                'updated_at' => '2018-11-22 11:34:34',
            ),
            43 => 
            array (
                'id' => 54,
                'path' => '/uploads/posts/landscape/images',
                'original_name' => 'climate-2-landscape.jpg',
                'caption' => 'Photograph by Stefania D\'Alessandro',
                'caption_ar' => 'تصوير ستيفانيا داليساندرو',
                'file_name' => '9436072d772493cb5e18862616d23929.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 14,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:34:35',
                'updated_at' => '2018-11-22 11:34:35',
            ),
            44 => 
            array (
                'id' => 55,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '1-landscape.jpg',
                'caption' => 'Photograph by Diane Mehanna',
                'caption_ar' => 'تصوير ديان مهنا',
                'file_name' => '8c4ef20d6ac21c7a9eac5d2f37ecaa02.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 16,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:57:49',
                'updated_at' => '2018-11-22 11:57:49',
            ),
            45 => 
            array (
                'id' => 56,
                'path' => '/uploads/pages/landscape/images',
                'original_name' => '2-landscape.jpg',
                'caption' => 'Construction drawing of Al-Qasimiyah School, 1982',
                'caption_ar' => 'مخطّط انشائي لمدرسة القاسمية، 1982',
                'file_name' => '083461fba03fbabc7954018a4d6aa493.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'landscape',
                'uploadable_id' => 17,
                'uploadable_type' => 'App\\Models\\PageImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 11:58:24',
                'updated_at' => '2018-11-22 11:58:24',
            ),
            46 => 
            array (
                'id' => 57,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'July 2,2018_SHJTRN_Amin Alsaden appointed as the director_Arabic.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => 'fc3b87401c8030fd98c005077032d8fd.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 1,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:21:08',
                'updated_at' => '2018-11-22 12:21:08',
            ),
            47 => 
            array (
                'id' => 58,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'July 2 2018_SHJTRN_Amin Alsaden appointed as the director_English.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '9462d5c3d527ccc19d206a892025d56e.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 2,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:21:08',
                'updated_at' => '2018-11-22 12:21:08',
            ),
            48 => 
            array (
                'id' => 59,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'May 25, 2018_SHJTRN_Rights of Future Generations announced as the theme_Arabic.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '02c44f92f48742a2e613376aad040dba.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 3,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:21:43',
                'updated_at' => '2018-11-22 12:21:43',
            ),
            49 => 
            array (
                'id' => 60,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'May 25 2018_SHJTRN_Rights of Future Generations announced as the theme_English.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '58fba0db2a2812dc3ca6c497543418d4.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 4,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:21:43',
                'updated_at' => '2018-11-22 12:21:43',
            ),
            50 => 
            array (
                'id' => 61,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'May 9,2018_SHJTRN_Adrian Lahoud appointed curator_Arabic.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '388aac84f32cd005a92b5820a12910e3.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 5,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:22:18',
                'updated_at' => '2018-11-22 12:22:18',
            ),
            51 => 
            array (
                'id' => 62,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'May 9 2018_SHJTRN_Adrian Lahoud appointed curator_English.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '04372436d6f83be5051237562536f5c5.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 6,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:22:18',
                'updated_at' => '2018-11-22 12:22:18',
            ),
            52 => 
            array (
                'id' => 63,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'April 3,2018_SHJTRN_The first international platform on architecture_Arabic.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => '0c29e5874d38229de0524efa708f832b.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 7,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:22:45',
                'updated_at' => '2018-11-22 12:22:45',
            ),
            53 => 
            array (
                'id' => 64,
                'path' => '/uploads/posts/external_files',
                'original_name' => 'April 3 2018_SHJTRN_The first international platform on architecture_English.pdf',
                'caption' => NULL,
                'caption_ar' => NULL,
                'file_name' => 'c1c78a8c66ad1e69827b2839a90dc667.pdf',
                'mime_type' => 'application/pdf',
                'template' => '',
                'uploadable_id' => 8,
                'uploadable_type' => 'App\\Models\\ExternalFile',
                'status' => 0,
                'created_at' => '2018-11-22 12:22:45',
                'updated_at' => '2018-11-22 12:22:45',
            ),
            54 => 
            array (
                'id' => 65,
                'path' => '/uploads/posts/images',
                'original_name' => 'Amin-Alsaden,-Director-of-Sharjah-Architecture-Triennial.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'f8401b09f0c81eadd8884b23a41a1e68.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 17,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 12:23:02',
                'updated_at' => '2018-11-22 12:23:02',
            ),
            55 => 
            array (
                'id' => 66,
                'path' => '/uploads/posts/images',
                'original_name' => 'Drone-image-of-aerial-view-from-Al-Sharq-street-overlooking-Khalid-Port,-Sharjah.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '5a383cf2e1fabf91e152281a9597e1d8.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 18,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 12:23:09',
                'updated_at' => '2018-11-22 12:23:09',
            ),
            56 => 
            array (
                'id' => 67,
                'path' => '/uploads/posts/images',
                'original_name' => 'Adrian-Lahoud,-Curator-of-the-first-Sharjah-Architecture-Triennial,-photo--Rabee-Younes.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => '69a5019e3116c7ebf086f57111673466.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 19,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 12:23:16',
                'updated_at' => '2018-11-22 12:23:16',
            ),
            57 => 
            array (
                'id' => 68,
                'path' => '/uploads/posts/images',
                'original_name' => 'Aerial-view-of-Corniche-Street-and-Al-Mujarrah-neighborhood.jpg',
                'caption' => '',
                'caption_ar' => '',
                'file_name' => 'f742a66cad93f5464aacd37177fa614b.jpg',
                'mime_type' => 'image/jpeg',
                'template' => 'square',
                'uploadable_id' => 20,
                'uploadable_type' => 'App\\Models\\PostImageSlide',
                'status' => 0,
                'created_at' => '2018-11-22 12:23:23',
                'updated_at' => '2018-11-22 12:23:23',
            ),
        ));
        
        
    }
}
